# Generated by Django 4.1.1 on 2022-10-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_cover_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userprofile'),
        ),
    ]
